In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
i=45

In [4]:
print(7)

7


In [5]:
print(i)

45


# Welcome to Numpy Tutorials

In [6]:
d=78

In [7]:
d

78

***this***

# Numpy Tutorial

In [8]:
import numpy as np

In [9]:
myarr=np.arange(21)

In [10]:
print(myarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
myar=np.array([3,6,684,7],np.int64)

In [12]:
myar[1]

6

In [13]:
myar=np.array([[3,6,684,7],[2,4,5,8]],np.int64)

In [14]:
myar[0,2]

684

In [15]:
myar.shape

(2, 4)

In [16]:
myar.dtype

dtype('int64')

In [17]:
myar[0,2]=64

In [18]:
myar

array([[ 3,  6, 64,  7],
       [ 2,  4,  5,  8]], dtype=int64)

In [19]:
myar[0,2]

64

# There are five different types for create array in numpy

# ***1) Array creation conversion from other python structure

In [20]:
myarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
myarray.dtype

dtype('int32')

In [23]:
myarray.shape

(3, 3)

In [24]:
myarray.size

9

In [25]:
np.array({34,25,65,25,43,34})

array({65, 34, 43, 25}, dtype=object)

# *** 2)Intrinsic numpy array creation objects

In [26]:
zeros=np.zeros((3,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
zeros.shape

(3, 5)

In [29]:
zeros.size

15

In [30]:
rng=np.arange(21)

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
lspace=np.linspace(1,50,11)

In [33]:
lspace

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1, 50. ])

In [34]:
lspace=np.linspace(1,5,4)

In [35]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
emp=np.empty((4,6))

In [37]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        2.22522597e-306, 1.33511969e-306, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 1.60217812e-306],
       [1.37961370e-306, 8.01091099e-307, 8.90104239e-307,
        1.11260144e-306, 1.02360256e-306, 8.34451504e-308],
       [1.39071445e-307, 1.33511562e-306, 8.90103560e-307,
        1.42410974e-306, 1.00132228e-307, 1.33511969e-306]])

In [38]:
emp_like=np.empty_like(lspace)

In [39]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [40]:
ide=np.identity(4)

In [41]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
ide.shape

(4, 4)

In [43]:
arr=np.arange(101)

In [44]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [45]:
arr=np.arange(99)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [48]:
arr=arr.reshape(33,3)

In [49]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [50]:
arr=arr.reshape(33,3)

In [51]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [52]:
arr=arr.ravel()

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr.shape

(99,)

In [55]:
x=[[1,2,3],[7,8,9]]


In [56]:
ar=np.array(x)

In [57]:
ar

array([[1, 2, 3],
       [7, 8, 9]])

In [58]:
a=ar.sum(axis=0)

In [59]:
a

array([ 8, 10, 12])

In [60]:
b=ar.sum(axis=1)

In [61]:
b

array([ 6, 24])

In [62]:
a.T


array([ 8, 10, 12])

In [63]:
ar.T

array([[1, 7],
       [2, 8],
       [3, 9]])

In [64]:
ar=ar.T

In [65]:
ar

array([[1, 7],
       [2, 8],
       [3, 9]])

In [66]:
ar=ar.T

In [67]:
ar

array([[1, 2, 3],
       [7, 8, 9]])

In [68]:
ar.flat

In [69]:
for i in ar.flat:
    print(i)

1
2
3
7
8
9


In [70]:
ar.ndim

2

In [71]:
ar=ar.T


In [72]:
ar

array([[1, 7],
       [2, 8],
       [3, 9]])

In [73]:
ar

array([[1, 7],
       [2, 8],
       [3, 9]])

In [74]:
ar.ndim

2

In [75]:
ar.size

6

In [76]:
ar.nbytes

24

In [77]:
ar.dtype

dtype('int32')

In [78]:
one=np.array([1,2,3,4,5,6,87,57,48,98,27,45])

In [79]:
one.argmax()

9

In [80]:
one[9]

98

In [81]:
one.argmin()

0

In [82]:
one.argsort()

array([ 0,  1,  2,  3,  4,  5, 10, 11,  8,  7,  6,  9], dtype=int64)

In [83]:
ar

array([[1, 7],
       [2, 8],
       [3, 9]])

In [84]:
ar.argmin()

0

In [85]:
ar.argmax()

5

In [86]:
ar.argmax(axis=0)

array([2, 2], dtype=int64)

In [87]:
ar[1,0]=45

In [88]:
ar

array([[ 1,  7],
       [45,  8],
       [ 3,  9]])

In [89]:
ar.argmax(axis=0)

array([1, 2], dtype=int64)

In [90]:
ar.argmin(axis=1)

array([0, 1, 0], dtype=int64)

In [91]:
ar.argsort(axis=0)

array([[0, 0],
       [2, 1],
       [1, 2]], dtype=int64)

In [92]:
ar.ravel()

array([ 1,  7, 45,  8,  3,  9])

In [93]:
ar.reshape(3,2)

array([[ 1,  7],
       [45,  8],
       [ 3,  9]])

In [94]:
ar=ar.reshape(2,3)

In [95]:
ar

array([[ 1,  7, 45],
       [ 8,  3,  9]])

In [96]:
br=np.array([4,5,6,8,1,2])

In [97]:
br

array([4, 5, 6, 8, 1, 2])

In [98]:
br=br.reshape(2,3)

In [99]:
ar

array([[ 1,  7, 45],
       [ 8,  3,  9]])

In [100]:
br

array([[4, 5, 6],
       [8, 1, 2]])

In [101]:
ar+br

array([[ 5, 12, 51],
       [16,  4, 11]])

In [102]:
ar*br

array([[  4,  35, 270],
       [ 64,   3,  18]])

In [103]:
np.sqrt(ar)

array([[1.        , 2.64575131, 6.70820393],
       [2.82842712, 1.73205081, 3.        ]])

In [104]:
np.sqrt(br)

array([[2.        , 2.23606798, 2.44948974],
       [2.82842712, 1.        , 1.41421356]])

In [105]:
ar.sum()

73

In [106]:
ar.sum(axis=0)

array([ 9, 10, 54])

In [107]:
np.where(ar>5)

(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))

In [108]:
np.count_nonzero(ar)

6

In [109]:
ar[0,0]=0

In [110]:
ar[1,2]=0

In [111]:
ar

array([[ 0,  7, 45],
       [ 8,  3,  0]])

In [112]:
np.count_nonzero(ar)

4

In [113]:
ar.size

6

In [114]:
ar.size-np.count_nonzero(ar)

2

In [115]:
np.nonzero(ar)

(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [116]:
import sys

In [117]:
py_ar=[0,4,55,2]

In [118]:
npar=np.array(py_ar)

In [119]:
npar

array([ 0,  4, 55,  2])

In [120]:
sys.getsizeof(1)*len(py_ar)

112

In [121]:
npar.itemsize*npar.size

16